spring:
  cloud:
    gateway:
      routes:
        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/PRODUIT-SERVICE/produits/**

        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/CLIENT-SERVICE/clients/**

        - id: fournisseur-service
          uri: lb://FOURNISSEUR-SERVICE
          predicates:
            - Path=/FOURNISSEUR-SERVICE/fournisseurs/**
